[package]
name = "to-mut-proc-macro"
version = "0.1.0"
edition = "2021"
description = "Convert immutable reference to mutable reference."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.107"
quote = "1.0.23"
